# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_Transformations',
            fields=[
                ('large_url', models.TextField()),
                ('short_url', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_visited', models.IntegerField(default=0)),
            ],
        ),
    ]
